disabled_rules:
  - identifier_name
  - statement_position
  - nesting
included:
  - Source
  - Example/Source
reporter: "xcode"

identifier_name:
  min_length: 1
  allowed_symbols: ["_"]

cyclomatic_complexity:
  ignores_case_statements: true
